server:
  error:
    include-message: always
    include-binding-errors: always

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/authenticationdb
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        formate_sql: true
    show-sql: true
AuthenticationSpring:
  app:
    jwtCookieName: AuthenticationSpring
    jwtSecret: AuthenticationSpringSecretKey
    jwtExpirationMs: 86400000

